id: P003180
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 10:45:35.095885
source_metadata:
  id: bdr:W1KG23490
  title: ཕེ་ཌོ།
  author: ''
  volumes:
    f294de5fd0a74b6194d6cd1d6b3ce831:
      image_group_id: I1KG23536
      title: ''
      volume_number: 1
      total_pages: 102
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
